.devcontainer/devcontainer.json, src/app/_PageComponents/FetchList.ts, src/app/_PageComponents/Header.tsx, src/app/_PageComponents/SearchDate.tsx, src/app/_PageComponents/SearchLocation.tsx, src/app/_PageComponents/SearchPriceRange.tsx
Header는 돌아가도록 수정함
문법 맞지 않는 부분 다수 수정했으나, 아직 돌아가지 않는 부분이 많아 수정 필요해 보입니다.
=> NextJS 포팅 작업

src/@type/Type.ts
User, Post, Reservation, Request에 대한 타입을 새로 정의했습니다.
원래 있던 것에서 빠진 것도 있을 텐데, 부족한 것도 있고 데이터가 더 필요한 필드도 있을 겁니다.
필요하다면 백엔드로 다시 요청을 보내 처리해야 할 것입니다. 관련 백엔드 API가 없는 것도 있을 텐데 이 부분은 빨리 마련해 보겠습니다.
=> Feat: Type 정의

package-lock.json, package.json, src/@shared/components/Map/Map.tsx, src/app/PostType.ts, src/app/SearchSubletInfo/page.tsx
**SCRUM-번호**
비밀번호 초기화를 위한 ID 인증과 이메일 인증 구현
- ID 인증 후 비밀번호 초기화까지 넘어갔습니다. 과정 중에 애니메이션이 예술입니다.
페이지 전환 애니메이션 참고하길 바랍니다.
- 이메일 인증을 검증 받는 것과 업데이트가 연결되어있어서 따로 판 부분이 있습니다.
- ~~과 비교해서 검토하고 리뷰해주세요
- 너무 복잡하게 되어있어 기능만 간단히 리팩토링 후 자세한 내용 확인 부탁드립니다.
=> searchInfo

.devcontainer/devcontainer.json
- 시작 시 backend 폴더를 자동으로 update하도록 변경
- backend 저장소 커밋 업데이트함
=> Feat: devcontainer 업데이트

src/@core/Header/Desktop/Header.tsx, src/@shared/components/FetchList/FetchList.ts, src/@shared/components/Input/ImageInput.tsx, src/@shared/components/Popup/Popup.tsx, src/@shared/components/StaticComponents/StaticComponents.tsx, src/@store/UserLikeStore.ts, src/app/_PageComponents/Home/HomeChildren.tsx, src/app/_PageComponents/Home/components/HomeRoomContainer.tsx, src/app/_PageComponents/Home/components/RoomProfile.tsx, src/app/page.tsx
[Fix] 로그인한 유저의 우측 내비게이션바 안나오는 이유 -> 백엔드 반환명이 바뀜.
[Fix] 방 업로드 기능 복구 (백엔드 최신화 대응 및 리팩토링 보완).
[Fix] 방 불러오기 또 안보임 해결.
[ADD & FIX] 좋아요 누른 방 담는 전역 스토어 추가
Apply suggestions from code review
Apply suggestions from code review
Merge branch 'main' of https://github.com/ussr1285/ItHome
[fix] 캐시 관련 fix
=> [Fix] 헤더와 메인화면 오작동 fix

.devcontainer/devcontainer.json, package-lock.json, package.json, src/@type/Type.ts, src/app/ChatType.ts, src/app/test/chat/[chat_id]/page.tsx, src/app/test/chat/_Store/ChatStore.ts, src/app/test/chat/page.tsx, src/app/test/chat/socket.tsx
- 채팅을 테스트하기 위한 페이지를 업데이트했습니다. 여러 유저가 로그인하여 실시간으로 채팅을 주고받을 수 있습니다.
=> [Websocket] 타입 업데이트 및 예제코드 업데이트

package-lock.json, package.json, src/@shared/components/FetchList/FetchList.ts, src/@type/Type.ts, src/app/RequestType.ts, src/app/_PageComponents/Home/HomeChildren.tsx, src/app/profile/me/components/Blocks/PostSummaryBlock.tsx, src/app/profile/me/components/Blocks/ReservationSummaryBlock.tsx, src/app/profile/me/components/Info/GetPostRequest.tsx, src/app/profile/me/components/Info/ReservationByPostKeyInfo.tsx, src/app/profile/me/components/Info/ReservationProgress.tsx, src/app/profile/me/page.tsx, src/app/request/page.tsx, src/app/reservation/Components/Info/BookPaymentForm.tsx, src/app/reservation/Components/Info/BookPriceAndDate.tsx, src/app/reservation/Components/Info/BookRefundRule.tsx, src/app/reservation/page.tsx, src/app/test/chat/_Store/ChatStore.ts
결제 페이지 구축을 위해 필요한 기능들 구축했습니다. 이제 결제 기능과 요청 페이지를 약간 수정하면 완료됩니다.
프로세스가
요청 -> 승인 -> 확인이며 booking과 request 파일을 분리하였습니다.
코드 길이 너무 길어졌는지 잘 봐주세요..
=> [Fix & Add] 결제 기능 기반 구축

src/@store/BookingPopUpStore.ts, src/app/booking/page.tsx, src/app/profile/[UserId]/Components/UserImageProfile.tsx, src/app/profile/[UserId]/page.tsx, src/app/profile/me/components/Blocks/ReservationSummaryBlock.tsx, src/app/profile/me/components/UserProfile/PostListComponent.tsx, src/app/profile/me/page.tsx
미루고 미루던 외부 프로필 최신화 완료했으며, 이제 예약 요청 -> 예약 승인 이후 결제페이지로 이동하는 과정도 완료되었습니다.
bookinfo Zustand 좀 수정했습니다
짧은 코드라 특별히 없습니다.
=> [ADD] 외부 프로필 & 결제 완료페이지 이동

src/@shared/components/Popup/Popup.tsx, src/@shared/components/StaticComponents/StaticComponents.tsx, src/@shared/components/verifyComponents/Email.tsx, src/@shared/styles/Public.styles.ts, src/app/profile/[UserId]/Components/UserImageProfile.tsx, src/app/profile/me/components/Blocks/PostSummaryBlock.tsx, src/app/profile/me/components/UserImageProfile.tsx, src/app/profile/me/components/UserProfile/PostListComponent.tsx, src/app/profile/me/components/UserProfile/UserPrivateComponent.tsx, src/app/profile/me/page.tsx
디자인, 프로로필 이미지, 텍스트 등 불필요한 부분 삭제와 리디자인
특히 버튼 부분을 중심적으로 바꿨습니다. 그리고 텍스트 사이즈는 그냥 작은걸로 통일하는게 좋아 보입니다.
실행해보면 좋을듯.
=> [Fix] User profile

src/@core/Header/Desktop/Header.tsx, src/@shared/components/FetchList/FetchList.ts, src/@shared/components/Input/TextInputTag.tsx, src/@shared/components/Popup/Popup.tsx, src/@shared/components/StaticComponents/StaticComponents.tsx, src/@shared/components/loginComponents/Google.tsx, src/@shared/styles/Public.styles.ts, src/@store/GuestInfoStore.ts, src/@store/UserInfoStore.ts, src/app/profile/me/components/Dialog/PostUploadDialog.tsx, src/app/profile/me/components/Dialog/UserDeleteDialog.tsx, src/app/profile/me/components/UserProfile/UserPrivateComponent.tsx
=> 로그인, 로그아웃 그리고 유저 삭제

src/@core/Header/Desktop/Header.tsx, src/@core/Header/Desktop/components/Search/SearchInput.tsx, src/@shared/components/Popup/Popup.tsx, src/@shared/components/StaticComponents/StaticComponents.tsx, src/app/_PageComponents/Home/components/MarketingBanner.tsx, src/app/_PageComponents/Home/components/RoomProfile.tsx, src/app/profile/me/components/Blocks/PostSummaryBlock.tsx, src/app/profile/me/components/Dialog/PostEditDialog.tsx, src/app/profile/me/components/Dialog/PostUploadDialog.tsx, src/app/roominfo/[roomKey]/page.tsx
=> marketing 문의하기 가이드 보기 연결 완료

public/svgs/searchButtonWhite.svg, src/@core/Header/Desktop/Header.tsx, src/@core/Header/Desktop/components/Search/SearchInputMobile.tsx, src/@core/Header/Desktop/components/Search/components/MobileDashboardItem.tsx, src/@core/Header/Desktop/components/Search/components/SearchButton.tsx, src/@core/Header/Desktop/components/Search/components/SearchButtonWithBox.tsx, src/app/searchsubletinfo/page.tsx
닫기가 hover면 text-white가 되도록 되어있었네요.
본래 배경이 검정이었던 곳이라 그랬었는듯 합니다.
=> [Header] 모바일 검색 도구 토글 추가 및 닫기 fix

src/@core/Header/Desktop/Header.tsx, src/@core/Header/Desktop/components/Search/SearchInput.tsx, src/@shared/components/FetchList/FetchList.ts, src/@shared/components/Popup/Popup.tsx, src/@shared/components/loginComponents/Google.tsx, src/@store/LoginPopUpStore.ts, src/app/_PageComponents/Home/components/MarketingBanner.tsx, src/app/_PageComponents/Home/components/RoomProfile.tsx, src/app/savesublet/page.tsx
=> 마케팅 배너, 좋아요 기능, 글자수 제한

src/@core/Header/Desktop/Header.tsx, src/@core/Header/Desktop/components/Search/SearchInputMobile.tsx, src/@core/Header/Desktop/components/Search/components/SearchPriceRange.tsx, src/@shared/components/Input/DoubleSlideInput.tsx, src/@shared/components/Popup/Popup.tsx, src/app/profile/me/components/Dialog/PostUploadDialog.tsx
=> [Header] 슬라이더 수정 (step 추가) & 모바일 로고와 검색 돋보기 줄어드는 문제 해결.

src/@core/Header/Desktop/components/Search/components/MobileDashboardItem.tsx, src/@core/Header/Desktop/components/Search/components/SearchDate.tsx, src/@core/Header/Desktop/components/Search/components/SearchLocation.tsx, src/@core/Header/Desktop/components/Search/components/SearchPriceRange.tsx, src/@shared/components/Input/TextInputTag.tsx, src/@shared/components/Popup/Popup.tsx, src/app/profile/me/components/Dialog/PostUploadDialog.tsx, src/app/savesublet/page.tsx, src/app/searchsubletinfo/page.tsx
=> 디자인 개선 및 사소한 오류 해결

src/@shared/components/Input/DoubleDatePicker.jsx
[Input] 날짜 선택 input 비교 오류 Hotfix
=> Hotfix!!!! -------- [Input] 날짜 선택 input 비교 오류 Hotfix

package-lock.json, package.json, src/@core/Header/Desktop/GoogleAnalytics.tsx, src/app/layout.tsx, src/app/page.tsx
=> google Analytics

package-lock.json, package.json, src/@shared/components/FetchList/FetchList.ts, src/@shared/components/Input/ImageInput.tsx, src/@shared/components/Popup/Popup.tsx, src/@shared/components/loginComponents/Google.tsx, src/@shared/components/loginComponents/LoginContent.tsx, src/app/profile/me/components/Dialog/PostUploadDialog.tsx, src/app/profile/me/components/UserProfile/UserPrivateComponent.tsx
피드백 대량 수용했습니다. 프로덕션 모드로 변경도 우선될거 같습니다.
=> 피드백 수용 및 방 업로드, 회원가입, 로그인 등 진행 상황과 오류 알림

src/@shared/components/FetchList/FetchList.ts, src/@shared/components/Popup/Popup.tsx, src/app/_PageComponents/Home/components/MarketingBanner.tsx, src/app/profile/me/components/Dialog/UserDeleteDialog.tsx
=> 유저 삭제 기능 오류 해결 및 회원 가입 기능 재정리

next.config.mjs, package.json
=> [배포] 정적파일 생성을 위한 설정

src/app/_PageComponents/Home/components/MarketingBanner.tsx, src/app/savesublet/SavePost.tsx, src/app/savesublet/page.tsx
=> savesublet build 모드

src/@shared/components/Map/Map.tsx, src/@shared/components/Popup/Popup.tsx, src/app/_PageComponents/Home/components/RoomProfile.tsx, src/app/profile/me/components/Blocks/PostSummaryBlock.tsx, src/app/profile/me/components/Dialog/PostUploadDialog.tsx, src/app/profile/me/components/UserProfile/PostListComponent.tsx, src/app/roominfo/[roomKey]/page.tsx
=> 지도 주소 기능, 방 올리기 버튼

src/app/_PageComponents/Home/HomeLayout.tsx, src/app/_PageComponents/Home/components/RoomProfile.tsx, src/app/roominfo/[roomKey]/page.tsx
=> 이미지, 홈페이지 처리
